layout_spectrum: 0
typography_spectrum: 0.4656284
color:
  saturation: 0.9542156
  lightness: 0.1357013
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#BD4487'
    - '#212121'
    - '#7F2880'
    - '#5C5C5C'
  rhythmicContrast: 0.3141608
name: gretchen
