name: gretchen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4656284
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#BD4487'
    - '#212121'
    - '#7F2880'
    - '#5C5C5C'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.3141608
purpose: []
